### ISSUE TITLE
如何添加标题栏？

### ISSUE THREAD

**Issue by seaguest** [DandreYang/YFViewPager#2]
你好，

如果我想在TAB上面增加一个标题栏和一个后退的按钮，该怎么实现？

**Comment by saxue** [comment]
你为什么不用导航？YFViewPager目前实现你的需求，需要你自己手动更改代码。

**Comment by seaguest** [comment]
:)
谢谢，我是新手，有些属于描述的不太清楚。
具体方法是:
YFViewPager 里面的UIScrollView *scrollView上面添加一个NavigationBar吗？
